# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-06-11 07:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField()),
                ('full_name', models.CharField(max_length=254)),
                ('email', models.EmailField(blank=True, max_length=70, null=True, unique=True)),
                ('mobile_no', models.IntegerField()),
            ],
        ),
    ]
